apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic-tidb-cluster
  namespace: tidb-system
spec:
  version: v5.1.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  imagePullPolicy: IfNotPresent
  discovery: { }
  pd:
    baseImage: uhub.service.ucloud.cn/pingcap/pd
    replicas: 3
    storageClassName: openebs-jiva-csi-sc
    requests:
      storage: "50Gi"
    config: { }
  tikv:
    baseImage: uhub.service.ucloud.cn/pingcap/tikv
    replicas: 3
    storageClassName: openebs-jiva-csi-sc
    requests:
      storage: "50Gi"
    config:
      storage:
        reserve-space: "0MB"
      rocksdb:
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tidb:
    baseImage: uhub.service.ucloud.cn/pingcap/tidb
    replicas: 2
    service:
      type: ClusterIP
    config: { }

---
apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: basic-tidb-monitor
  namespace: tidb-system
spec:
  clusters:
    - name: basic-tidb-cluster
  prometheus:
    baseImage: prom/prometheus
    version: v2.18.1
  grafana:
    baseImage: grafana/grafana
    version: 7.5.7
  initializer:
    baseImage: uhub.service.ucloud.cn/pingcap/tidb-monitor-initializer
    version: v5.1.0
  reloader:
    baseImage: uhub.service.ucloud.cn/pingcap/tidb-monitor-reloader
    version: v1.0.1
  imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Secret
metadata:
  name: tidb-secret
  namespace: tidb-system
  labels:
    app.kubernetes.io/name: tidb
    app.kubernetes.io/instance: my-tidb
type: Opaque
data:
  root: "QVZIZHJjcWkyUQ=="
---
apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  name: db-init
  namespace: tidb-system
spec:
  image: tnir/mysqlclient
  imagePullPolicy: IfNotPresent
  cluster:
    namespace: tidb-system
    name: basic-tidb-cluster
  passwordSecret: tidb-secret