# Copyright © 2021 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: sealer.aliyun.com/v1alpha1
kind: Cluster
metadata:
  name: my-cluster
spec:
  image: registry.cn-qingdao.aliyuncs.com/sealer-app/my-SAAS-all-inone:latest
  provider: BAREMETAL
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: mysql-config
spec:
  path: etc/mysql.yaml
  data: |
     test
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: redis-config
spec:
  path: etc/redis.yaml
  data: |
    test

---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Config
metadata:
  name: REGISTRY
spec:
  path: etc/registry.yaml
  data: |
    domain: image.cai-inc.com
    ip: 172.16.0.1
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: ETCD_BACKUP
spec:
  action: Manual
  data: |
    alioss:
       ossendpoint: oss-cn-hangzhou.aliyuncs.com
       accesskeyid: *****
       accesskeysecrets: ****
       bucketname: etcdbackup
       objectpath: /sealos/
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: HOSTNAME
spec:
  data: |
    192.168.0.2 master-0
    192.168.0.3 master-1
    192.168.0.4 master-2
    192.168.0.5 node-0
    192.168.0.6 node-1
    192.168.0.7 node-2
---
apiVersion: sealer.aliyun.com/v1alpha1
kind: Plugin
metadata:
  name: SHELL
spec:
  action: PostInstall
  on: role=master
  data: |
    kubectl taint nodes node-role.kubernetes.io/master=:NoSchedule
  ---
  apiVersion: sealer.aliyun.com/v1alpha1
  kind: Plugin
  metadata:
    name: LABEL
  spec:
    data: |
      192.168.0.2 ssd=true
      192.168.0.3 ssd=true
      192.168.0.4 ssd=true
      192.168.0.5 ssd=false,hdd=true
      192.168.0.6 ssd=false,hdd=true
      192.168.0.7 ssd=false,hdd=true